[package]
name = "test-with"
version = "0.1.0"
authors = ["Antonio Yang <yanganto@gmail.com>"]
edition = "2021"
license = "MIT"
description = "A lib help you run test with condition"
repository = "https://github.com/yanganto/test-with"

[lib]
proc-macro = true

[dependencies]
regex = "1"
proc-macro2 = "1.0.36"
proc-macro-error = "1.0.4"
